name: Build MERA RESET APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz repo
        uses: actions/checkout@v4

      - name: Rozpakuj projekt
        run: |
          rm -rf buildsrc
          mkdir buildsrc
          unzip -q "MERA_RESET_ANDROID_PROJECT_ALL_MUSIC.zip" -d buildsrc

      - name: Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Zestaw SDK dla Androida
        uses: android-actions/setup-android@v4
        with:
          packages: 'platform-tools'

      - name: Zainstaluj Android 35
        run: |
          sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Popraw ikonę aplikacji
        run: |
          sed -i 's|@drawable/ic_launcher|@mipmap/ic_launcher|g' buildsrc/MERA_RESET_ANDROID/app/src/main/AndroidManifest.xml

      - name: Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Zbuduj APK
        working-directory: buildsrc/MERA_RESET_ANDROID
        run: gradle --no-daemon assembleDebug

      - name: Nazwij APK
        run: |
          cp buildsrc/MERA_RESET_ANDROID/app/build/outputs/apk/debug/app-debug.apk MERA_RESET.apk

      - name: Zapisz APK
        uses: actions/upload-artifact@v4
        with:
          name: MERA_RESET_APK
          path: MERA_RESET.apk
